// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLqlQHfmRr4QxCe2TrMXy5dlcjU8jxBdo',
    appId: '1:569844317314:android:a5cd145dc541fc82c4889b',
    messagingSenderId: '569844317314',
    projectId: 'rendezvous-beta-v3',
    storageBucket: 'rendezvous-beta-v3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWt1CV1BN8sUcE7KbG3XYtaSlOsWFb49I',
    appId: '1:569844317314:ios:622f992a92db33b8c4889b',
    messagingSenderId: '569844317314',
    projectId: 'rendezvous-beta-v3',
    storageBucket: 'rendezvous-beta-v3.appspot.com',
    iosClientId: '569844317314-b0tls7ejgf6lm6nr3tnuo6e2k1u8bpbo.apps.googleusercontent.com',
    iosBundleId: 'com.michaelmay.rendezvousBetaV3',
  );
}
